Repository GSG-CF05/DonationApp-Team-4, pull requests merged in 2022-02, with the labels that each got.

#2 Create the file structure for donation app project
  After signup/after-signup.css
  After signup/after-signup.html
  Inside fundraiser1/inside-fundraiser1.css
  Inside fundraiser1/inside-fundraiser1.html
  See blog/see-blog.css
  See blog/see-blog.html
  index.html
  style.css
Labels: Done

#4 add the images folder
  images/on-boarding.png
Labels: Done

#10 images added
  images/Ellipse 36 (1).png
  images/Ellipse 36.png
  images/Ellipse 37.png
  images/Ellipse 38.png
  images/Ellipse 39.png
  images/Ellipse 40.png
  images/Rectangle 1485 (1).png
  images/Rectangle 1485.png
  images/unsplash_fZRpn21atJs.png
  images/unsplash_yg1Zayn0Few.png
Labels: For review

#11 html structure added
  index.html
  style.css
Labels: Approved

#14 buttons fixed
  index.html
  style.css
Labels: For review

#15 create and style after signup page for donationapp project
  After signup/after-signup.css
  After signup/after-signup.html
  images/hand.svg
Labels: For review

#19 edit href in a tag in compaign section
  After signup/after-signup.html
Labels: For review

#17 Creating and style for inside fundraiser page
  Inside fundraiser1/img/1.png
  Inside fundraiser1/img/2.png
  Inside fundraiser1/img/3.png
  Inside fundraiser1/img/4.png
  Inside fundraiser1/img/Rectangle 1485 (1).png
  Inside fundraiser1/img/arrow-right-1 1.png
  Inside fundraiser1/img/back.svg
  Inside fundraiser1/img/bg.svg
  Inside fundraiser1/img/heart-circle 4.png
  Inside fundraiser1/img/line.png
  Inside fundraiser1/img/monika.png
  Inside fundraiser1/img/more 1.png
  Inside fundraiser1/img/timer-1 2.png
  Inside fundraiser1/inside-fundraiser1.css
  Inside fundraiser1/inside-fundraiser1.html
Labels: Approved

#20 13 add readme file
  README.md
  final-result/1.png
  final-result/2.png
  final-result/3.png
  final-result/4.png
Labels: For review
